#include <string>
#include <unordered_map>

std::unordered_map<std::string, std::string> lora_mapping = {
    {"cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_0_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_0_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_0_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_0_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_0_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_0_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_1_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_1_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_1_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_1_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_1_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_1_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.10.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_10_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.10.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_10_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_10_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_10_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_10_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.10.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_10_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.11.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_11_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.11.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_11_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_11_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_11_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_11_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.11.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_11_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_2_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_2_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_2_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_2_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_2_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_2_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_3_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_3_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_3_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_3_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_3_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_3_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_4_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_4_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_4_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_4_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_4_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_4_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_5_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_5_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_5_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_5_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_5_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_5_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_6_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_6_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_6_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_6_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_6_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_6_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_7_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_7_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_7_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_7_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_7_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_7_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.8.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_8_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.8.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_8_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_8_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_8_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_8_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_8_self_attn_v_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.9.mlp.fc1.weight",
     "lora_te_text_model_encoder_layers_9_mlp_fc1"},
    {"cond_stage_model.transformer.text_model.encoder.layers.9.mlp.fc2.weight",
     "lora_te_text_model_encoder_layers_9_mlp_fc2"},
    {"cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.k_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_9_self_attn_k_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.out_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_9_self_attn_out_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.q_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_9_self_attn_q_proj"},
    {"cond_stage_model.transformer.text_model.encoder.layers.9.self_attn.v_"
     "proj.weight",
     "lora_te_text_model_encoder_layers_9_self_attn_v_proj"},
    {"model.diffusion_model.input_blocks.1.1.proj_in.weight",
     "lora_unet_down_blocks_0_attentions_0_proj_in"},
    {"model.diffusion_model.input_blocks.1.1.proj_out.weight",
     "lora_unet_down_blocks_0_attentions_0_proj_out"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out."
     "0.weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out."
     "0.weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn2_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_down_blocks_0_attentions_0_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.input_blocks.2.1.proj_in.weight",
     "lora_unet_down_blocks_0_attentions_1_proj_in"},
    {"model.diffusion_model.input_blocks.2.1.proj_out.weight",
     "lora_unet_down_blocks_0_attentions_1_proj_out"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out."
     "0.weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn1_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out."
     "0.weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn2_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_down_blocks_0_attentions_1_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.input_blocks.4.1.proj_in.weight",
     "lora_unet_down_blocks_1_attentions_0_proj_in"},
    {"model.diffusion_model.input_blocks.4.1.proj_out.weight",
     "lora_unet_down_blocks_1_attentions_0_proj_out"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out."
     "0.weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn1_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out."
     "0.weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn2_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_down_blocks_1_attentions_0_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.input_blocks.5.1.proj_in.weight",
     "lora_unet_down_blocks_1_attentions_1_proj_in"},
    {"model.diffusion_model.input_blocks.5.1.proj_out.weight",
     "lora_unet_down_blocks_1_attentions_1_proj_out"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out."
     "0.weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn1_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out."
     "0.weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn2_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_down_blocks_1_attentions_1_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.input_blocks.7.1.proj_in.weight",
     "lora_unet_down_blocks_2_attentions_0_proj_in"},
    {"model.diffusion_model.input_blocks.7.1.proj_out.weight",
     "lora_unet_down_blocks_2_attentions_0_proj_out"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out."
     "0.weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn1_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out."
     "0.weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn2_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_down_blocks_2_attentions_0_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.input_blocks.8.1.proj_in.weight",
     "lora_unet_down_blocks_2_attentions_1_proj_in"},
    {"model.diffusion_model.input_blocks.8.1.proj_out.weight",
     "lora_unet_down_blocks_2_attentions_1_proj_out"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out."
     "0.weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn1_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out."
     "0.weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn2_to_out_"
     "0"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_down_blocks_2_attentions_1_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.middle_block.1.proj_in.weight",
     "lora_unet_mid_block_attentions_0_proj_in"},
    {"model.diffusion_model.middle_block.1.proj_out.weight",
     "lora_unet_mid_block_attentions_0_proj_out"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_mid_block_attentions_0_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.10.1.proj_in.weight",
     "lora_unet_up_blocks_3_attentions_1_proj_in"},
    {"model.diffusion_model.output_blocks.10.1.proj_out.weight",
     "lora_unet_up_blocks_3_attentions_1_proj_out"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_3_attentions_1_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.11.1.proj_in.weight",
     "lora_unet_up_blocks_3_attentions_2_proj_in"},
    {"model.diffusion_model.output_blocks.11.1.proj_out.weight",
     "lora_unet_up_blocks_3_attentions_2_proj_out"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_3_attentions_2_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.3.1.proj_in.weight",
     "lora_unet_up_blocks_1_attentions_0_proj_in"},
    {"model.diffusion_model.output_blocks.3.1.proj_out.weight",
     "lora_unet_up_blocks_1_attentions_0_proj_out"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_1_attentions_0_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.4.1.proj_in.weight",
     "lora_unet_up_blocks_1_attentions_1_proj_in"},
    {"model.diffusion_model.output_blocks.4.1.proj_out.weight",
     "lora_unet_up_blocks_1_attentions_1_proj_out"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_1_attentions_1_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.5.1.proj_in.weight",
     "lora_unet_up_blocks_1_attentions_2_proj_in"},
    {"model.diffusion_model.output_blocks.5.1.proj_out.weight",
     "lora_unet_up_blocks_1_attentions_2_proj_out"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_1_attentions_2_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.6.1.proj_in.weight",
     "lora_unet_up_blocks_2_attentions_0_proj_in"},
    {"model.diffusion_model.output_blocks.6.1.proj_out.weight",
     "lora_unet_up_blocks_2_attentions_0_proj_out"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_2_attentions_0_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.7.1.proj_in.weight",
     "lora_unet_up_blocks_2_attentions_1_proj_in"},
    {"model.diffusion_model.output_blocks.7.1.proj_out.weight",
     "lora_unet_up_blocks_2_attentions_1_proj_out"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_2_attentions_1_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.8.1.proj_in.weight",
     "lora_unet_up_blocks_2_attentions_2_proj_in"},
    {"model.diffusion_model.output_blocks.8.1.proj_out.weight",
     "lora_unet_up_blocks_2_attentions_2_proj_out"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_2_attentions_2_transformer_blocks_0_ff_net_2"},
    {"model.diffusion_model.output_blocks.9.1.proj_in.weight",
     "lora_unet_up_blocks_3_attentions_0_proj_in"},
    {"model.diffusion_model.output_blocks.9.1.proj_out.weight",
     "lora_unet_up_blocks_3_attentions_0_proj_out"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_k."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn1_to_k"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_"
     "out.0.weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn1_to_out_0"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_q."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn1_to_q"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_v."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn1_to_v"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_k."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn2_to_k"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_"
     "out.0.weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn2_to_out_0"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_q."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn2_to_q"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_v."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_attn2_to_v"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0."
     "proj.weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_ff_net_0_proj"},
    {"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2."
     "weight",
     "lora_unet_up_blocks_3_attentions_0_transformer_blocks_0_ff_net_2"},
};